server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimeZone=true&serverTimezone=UTC&useLegacyData
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto:drop -> case drop registers
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

#to create db: psql -U postgres postgres;
#create database academia;
#exit;
#psql -U postgres academia;
# \dt

